export enum UserRole {
    SUPER_ADMIN = 'SUPER_ADMIN',
    ADMIN = 'ADMIN',
    PHYSICIAN = 'PHYSICIAN',
    NURSE = 'NURSE',
    COORDINATOR = 'COORDINATOR',
    PATIENT = 'PATIENT',
    AUDITOR = 'AUDITOR',
}

export enum SeverityLevel {
    MILD = 'MILD',
    MODERATE = 'MODERATE',
    SEVERE = 'SEVERE',
    CRITICAL = 'CRITICAL',
}

export enum VitalParameterType {
    TEMPERATURE = 'TEMPERATURE',
    BLOOD_PRESSURE_SYSTOLIC = 'BLOOD_PRESSURE_SYSTOLIC',
    BLOOD_PRESSURE_DIASTOLIC = 'BLOOD_PRESSURE_DIASTOLIC',
    HEART_RATE = 'HEART_RATE',
    WEIGHT = 'WEIGHT',
}
